import { Inter } from "next/font/google";
import "./Assets/style.css";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CA Saurabh Srivastava",
  description: "Generated by create next app",
  icons: {
    icon: ["/images/favicon.ico?v=4"],
    apple: ["/images/apple-touch-icon.png?v=4"],
    shortcut: ["/images/apple-touch-icon"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="innerDashLayout">{children}</div>
      </body>
    </html>
  );
}
