import { Inter } from "next/font/google";
import "./globals.css";
// import "./Assets/style.css";
// import "./Dash/Assets/style.css";
import TopHeader from "@/app/(Root)/_components/TopHeader";
import Header from "@/app/(Root)/_components/Header";
import Watsdapp from "@/app/(Root)/_components/Watsdapp";
import CallButton from "@/app/(Root)/_components/CallButton";
import { headers } from "next/headers";
import Footer from "@/app/(Root)/_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CA Saurabh Srivastava",
  description: "Generated by create next app",
  icons: {
    icon: ["/images/favicon.ico?v=4"],
    apple: ["/images/apple-touch-icon.png?v=4"],
    shortcut: ["/images/apple-touch-icon"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: ` type="application/ld+json">{
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": "ca saurabh srivastava",
      "url": "https://casaurabhsrivastava.com",
      "logo": "https://casaurabhsrivastava.com/images/CA-Saurabh-logo.png",
      "contactPoint": {
        "@type": "ContactPoint",
        "telephone": "+919900085630",
        "contactType": "technical support",
        "areaServed": "IN",
        "availableLanguage": ["en","Hindi"]
      },
      "sameAs": [
        "https://www.facebook.com/casaurabhsrivastavavaluer/",
        "https://twitter.com/ca_srivastava",
        "https://www.instagram.com/ca_srivastava/",
        "https://www.linkedin.com/in/ca-saurabh-srivastava-valuer/",
        "https://casaurabhsrivastava.com/"
      ]
    }</script><script type="application/ld+json">{
      "@context": "https://schema.org/", 
      "@type": "product", 
      "name": "Expert CFO Services in Bangalore, India | Financial Forecasting & Taxation by CA Saurabh Srivastava",
      "image": "https://casaurabhsrivastava.com/images/saurabh.jpg",
      "description": "Elevate your business with top-notch CFO services in Bangalore. Specializing in financial forecasting, taxation services, and compliance with the Foreign Exchange Management Act. Get professional accounts, MIS, and taxation services in India by CA Saurabh Srivastava",
      "brand": {
        "@type": "Brand",
        "name": "CA SAURABH SRIVASTAVA"
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.9",
        "ratingCount": "5674"
      }
    }
    `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script', 'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '588554096735386');
      fbq('track', 'PageView');
      `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=588554096735386&ev=PageView&noscript=1"
          />
        </noscript>

        <script
          dangerouslySetInnerHTML={{
            __html: `
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script', 'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '1540042310064914');
      fbq('track', 'PageView');
    `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1540042310064914&ev=PageView&noscript=1"
          />
        </noscript>

        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-R4LWP0CM8K"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());
      gtag('config', 'G-R4LWP0CM8K');
      `,
          }}
        />

        <script
          dangerouslySetInnerHTML={{
            __html: `
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-M7TXJNMN');
      `,
          }}
        />

        <meta
          name="google-site-verification"
          content="aIyJIbORAybOw3k4YuZBI5b2lqv2aoZfUGucRcpM36s"
        />
        <meta name="msvalidate.01" content="2AAF2205AD84DDD38B43ACD4486DE972" />
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-M7TXJNMN"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
      </head>
      <body className={inter.className}>
        <div className="fromMainLayout">
          <TopHeader />
          <Header />
          <CallButton />
          <Watsdapp />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
